config/routes.rb
Rails.application.routes.draw do
 root controller: 'home', action: 'index'

 get "/about", controller: 'home', action: 'about', as: 'about'

 get "/teams", controller: 'home', action: 'teams', as: 'teams'

 get "/contact", controller: 'home', action: 'contact', as: 'contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def teams
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact.html.erb
This is our contacts page

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/teams.html.erb
This is the teams folder. 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Golfbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <ul class="nav nav-pills">
        <li class="nav-item"><%=link_to 'Home', root_url, {:class => "nav-link"} %></li>
        <li class="nav-item"><%=link_to 'About', about_url, {:class => "nav-link"} %></li>
        <li class="nav-item"><%=link_to 'Teams', teams_url, {:class => "nav-link"} %></li>
        <li class="nav-item"><%=link_to 'Contact', contact_url, {:class => "nav-link"} %></li>
      </ul>     
    </nav>
    <%= yield %>
  </body>
</html>